### ISSUE TITLE
请问该模拟冬日绘板脚本可以实现token功能吗

### ISSUE THREAD

**Issue by linmobi** [ouuan/fake-luogu-paintboard-server#20]

**Comment by linmobi** [comment]
POST(/paintBoard/paint)
此时就直接传入token参数吗

**Comment by ouuan** [comment]
2022 年的 API 是 token 作为 param，也就是 `/paintboard/paint?token=<token>`. 你看最后更新时间就可以知道，仓库里的代码没有更新，还是以前的用 Cookies 认证的 API。

**Comment by linmobi** [comment]
> 2022 年的 API 是 token 作为 param，也就是 .你看最后更新时间就可以知道，仓库里的代码没有更新，还是以前的用 Cookies 认证的 API。`/paintboard/paint?token=<token>`

好的，谢谢
